### ISSUE TITLE
Orientation estimate in sensor_msgs/Imu

### ISSUE THREAD

**Issue by horverno** [szenergy/duro_gps_driver#12]
In the `/gps/duro/imu` message the `orientation` is zero right now, although it is provided by the sensor in the message `/gps/duro/rollpitchyaw`. It needs to be converted to `geometry_msgs/Quaternion` and fill out in a proper way.

http://docs.ros.org/en/melodic/api/sensor_msgs/html/msg/Imu.html

**Comment by enricobellocchio** [comment]
Dear @horverno, do you have any updates on this aspect? do you have any suggestions for implementing this enhancement?

**Comment by horverno** [comment]
Dear @enricobellocchio i am planning to  implement this, it is quite easy to do, but right now i am a bit busy
basically what has to be done is to fill the `imu_ros_msg.orientation`  in [duro.cpp](https://github.com/szenergy/duro_gps_driver/blob/facebd385e2ddbe9a59000ae2bc2a66e437ca37c/src/duro.cpp#L246) with the proper quaternions form the sensor

**Comment by horverno** [comment]
@enricobellocchio i fixed it, but please note orientation is a slower, estimated value compared to the other IMU messages which are not calculated only published as raw data in the correct unit

**Comment by enricobellocchio** [comment]
Thank you very much!
