### ISSUE TITLE
Can't get orientation data from pose

### ISSUE THREAD

**Issue by skyetheguy** [szenergy/duro_gps_driver#2]
How can I get the orientation data? Right now the only non-zero values I get from the pose is the position (x, y, z). I'm using a swift multi in simulation mode with msg IDs 544 and 545 enabled for tcp server 0.

But in the swift sbp spec document it says swift multi and duro do not produce these messages (544 and 545)...

https://www.swiftnav.com/latest/sbp-specification

**Comment by horverno** [comment]
Duro does provide orientation, we are using it that way. I never used the Piksi Multi, but I'm guessing Multi also has an inertial and a non inertial version like Duro. Are you using the inertial one? If yes, did you enable the IMU?

**Comment by skyetheguy** [comment]
Ah, I didn't realise they had "inertial" versions of the products.. I don't think there is an inertial version of the multi though as I don't see one on their store. 

I do have the IMU enabled but I'm guessing this feature is reserved only for the Duro Inertial and not the regular Duro?

**Comment by horverno** [comment]
Yes, i think it is  is reserved only for the Duro Inertial, but if you want to be 100% sure you should ask the Swiftnav support, they reply quite quickly.
