### ISSUE TITLE
Node outputs orientation data not provided by Duro or Piksi

### ISSUE THREAD

**Issue by rokusottervanger** [szenergy/duro_gps_driver#4]
According to the docs of libsbp, the orientation data published in the "pose" and "odom" messages from the Duro driver node are not provided by Duro or Piksi: https://swift-nav.github.io/libsbp/c/build/docs/html/group__orientation.html
Only the baseline direction is provided, but this is not to be confused with the Duro 's orientation.

**Comment by horverno** [comment]
Orientation does not rely on using the baseline heading (`0x020F`), instead the vehicle body frame's orientation quaternion  (`0x0220`) is used.

**Comment by rokusottervanger** [comment]
According to the manual "This message will only be available in future INS versions
of Swift Products and is not produced by Piksi Multi or Duro."
