### ISSUE TITLE
Status flags are not correct

### ISSUE THREAD

**Issue by rokusottervanger** [szenergy/duro_gps_driver#5]
The status flags for the position message are described in the PDF that can be found here: http://swift-nav.github.io/libsbp/
The status byte should be bitmasked before it can be interpreted as an integer value. Are you interested in a PR?

**Comment by horverno** [comment]
Thanks @rokusottervanger the bitmasked solution would result a more straightforward code. PR is welcome of course. 
https://github.com/szenergy/duro_gps_driver/blob/fa11077a223896142b0a0be7e27d90eca3f59801/src/duro.cpp#L143

**Comment by rokusottervanger** [comment]
It's not only more straightforward. The current implementation leads to the wrong output. This is not an enhancement, it's a bug.

**Comment by horverno** [comment]
This issue made me curious, so i added the bitmasked version of the code, is this how you imagined it?

**Comment by horverno** [comment]
thanks for the contribution @rokusottervanger
