### ISSUE TITLE
Let a driver be a driver: UTM conversion should be separate functionality

### ISSUE THREAD

**Issue by rokusottervanger** [szenergy/duro_gps_driver#6]
There is now a conversion from lat long to UTM coordinates in this driver. IMHO I think you should let the driver be a driver, and perform UTM conversion separately and independently if necessary. Just use the regular ROS message types like `sensor_msgs/NavSatFix` and you'll be able to swap devices without the need to implement a new driver that performs UTM conversion like this one. It makes for a more flexible and lean system. 

For example, for my use case, I don't need UTM conversion, but using this driver forces me to take on the extra weight of the UTM conversion for no reason.

**Comment by horverno** [comment]
I see your opinion, but for our purposes UTM is obligatory. I think what we can do is add an ROS param to disable the UTM topics. What do you think?

**Comment by rokusottervanger** [comment]
I think you should split the functionality up into a driver node and a UTM conversion node. Here are a couple of reasons:

- The UTM conversion node might also be convenient for other people/teams that use different GPS receivers.
- The driver node might also be convenient for other people/teams that don't use UTM.
- A user of your UTM conversion code (for example: you) can switch GPS devices without having to implement a new UTM converion.
- A user of your driver code can use any coordinate frame convention he/she desires, without the (slight, but still) overhead of UTM conversion.

BTW, IMHO this UTM conversion should be in a separate package, maybe even a separate repository, as it is not coupled to any GNSS system or its driver's implementation.

**Comment by horverno** [comment]
I see it differently, here are my reasons:
- All of the other GPS we used had UTM stream as default (NovAtel, GEO-FOG 3D KVH, etc)
- This also allows Swift ​​Navigation​ Duro Inertial to provide comparable output to other manufacturers 
- This driver was designed for robotics use:
  - SwiftNav cooperated with Carnegie Robotics
  - This is an ROS driver, not a general purpose one
- ROS used SI units, and UTM uses meters which is a fit
- Self-driving platforms such as Apollo or Autoware also rely on UTM
- The `UTM.h` has no dependencies whatsoever, so it is quite protable and as you mentioned it is a slight overhead only

Besides that the suggested _rosparam disable UTM version_ would even abolish the slight overhead too, and you could use the driver as you intended to. 
On the other hand I think it is a good idea to create UTM conversion package (if it is not yet done already).

**Comment by rokusottervanger** [comment]
Great argumentation. In light of that, it sounds like a good decision. Thanks for the elaborate answer!
